#!/usr/bin/env python3
"""boot_cfg.inc for boot.asm: what the boot loader's machine check needs to
know about THIS build, and the screen it shows while it checks.

  BOOT_TOPBANK   the highest linear-RAM bank the port uses (tools/bank_map.py's
                 regions, priced from the same equates the engine indexes
                 with): the loader probes every bank $01..BOOT_TOPBANK
  B_MCOL         the column of a check's mark
  BOOT_RELOC     where the VBXE-at-$D7xx table loads (tools/vbxe_reloc.py)
and boot_rows.inc, its screen: DOOM in block letters, the port's name and the
build's version, the three checks, the two status rows -- and the texts that
go into those (loading, or the part that is missing).

Run by build_atr.ps1 after the layout is emitted and before boot.asm is
assembled.

    python tools/boot_cfg.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import bank_map                                                   # noqa: E402

W = 40
LOGO = ('######   #####   #####  ##   ##',
        '##   ## ##   ## ##   ## ### ###',
        '##   ## ##   ## ##   ## #######',
        '##   ## ##   ## ##   ## ## # ##',
        '##   ## ##   ## ##   ## ##   ##',
        '##   ## ##   ## ##   ## ##   ##',
        '######   #####   #####  ##   ##')
BLOCK = 0x80                         # the inverse space: a solid cell


def top_bank():
    top = 0
    for name, base, size, _what, _note, _span in bank_map.REGIONS:
        try:
            hi = bank_map.v(base) + bank_map.v(size) - 1
        except bank_map.Unresolved as e:
            sys.exit(f'boot_cfg: {name}: {e}')
        top = max(top, hi >> 16)
    if not 1 <= top <= 0xFE:
        sys.exit(f'boot_cfg: the top bank came out ${top:02X}')
    return top


def screen(text):
    """ASCII -> ANTIC screen codes, centred on a 40-column row."""
    if len(text) > W:
        sys.exit(f'boot_cfg: {text!r} is wider than the screen')
    out = []
    for c in text.center(W).upper():
        o = ord(c)
        out.append(o - 0x20 if 0x20 <= o < 0x60 else o)
    return out


def version():
    try:
        n = int(open(os.path.join(ROOT, 'VERSION')).read().strip())
    except (OSError, ValueError):
        n = 1
    return '%d.%02d' % divmod(n, 100)


MARK_COL = 28                        # where a check's OK / MISSING! goes
BOOT_RELOC = 0x1500                  # the VBXE-at-$D7xx table's load address: RAM no
                                     #   XEX segment loads into (make_atr_doom.py
                                     #   checks), read by the boot loader alone
CHECKS = ('65C816 CPU', 'LINEAR RAM $01-$%02X', 'VBXE FX CORE 1.2X')
# two rows under the list: what is loading, or what is missing
LOADING = ('LOADING...', '')
ERRORS = (('THIS GAME NEEDS A 65C816 CPU.', ''),
          ('NO LINEAR RAM AT BANK $##.', 'THIS GAME NEEDS IT UP TO BANK $%02X.'),
          ('NO VBXE WITH FX CORE 1.2X', 'AT $D640 OR $D740.'))
# the ANTONIA II image's boot (boot.asm -d:ANTONIA2): the CPU row also covers
# the card's multiplier/divider -- the loader has no bytes for a fourth row
ANT2_CHECK0 = '65C816 CPU + MUL/DIV'
ANT2_ERROR0 = ('THIS IMAGE NEEDS ANTONIA II: A 65C816', 'AND ITS MULTIPLIER/DIVIDER AT $FFF008.')


def dta(codes):
    return '        dta ' + ','.join('$%02X' % b for b in codes)


def main():
    top = top_bank()
    nl = chr(10)
    hdr = '; AUTO-GENERATED by tools/boot_cfg.py -- do not edit.' + nl
    out = [hdr.rstrip(), '; --- the screen, rows of 40 in the display list order']
    out.append('b_logo')
    for ln in LOGO:
        out.append(dta([BLOCK if c == '#' else 0 for c in ln.center(W)]))
    out.append('b_title')
    out.append(dta(screen(f'VBXE AI (65816)  V{version()}  BY W1K')))
    out.append('b_chk')

    def check_row(label):
        row = ('    ' + label + ' ').ljust(MARK_COL - 1, '.') + ' '
        return dta(screen(row.ljust(W)))
    for i, c in enumerate(CHECKS):
        label = c % top if '%' in c else c
        if i == 0:                   # one row either way: the same bytes count
            out += [' .ifdef ANTONIA2', check_row(ANT2_CHECK0), ' .else',
                    check_row(label), ' .endif']
        else:
            out.append(check_row(label))
    out.append('b_stat')
    out.append('        :80 dta 0')
    out.append('; --- ... and what goes into b_stat')
    ebank = None
    for name, (l1, l2) in (('b_load', LOADING),) + tuple(
            ('b_e%d' % i, e) for i, e in enumerate(ERRORS)):
        out.append(name)
        r1 = l1.center(W)
        if '##' in r1:
            ebank = (name, r1.index('##'))
        rows = [dta(screen(r1)), dta(screen(l2 % top if '%' in l2 else l2))]
        if name == 'b_e0':
            out += [' .ifdef ANTONIA2', dta(screen(ANT2_ERROR0[0])),
                    dta(screen(ANT2_ERROR0[1])), ' .else'] + rows + [' .endif']
        else:
            out += rows
    out.append('b_ebank = %s+%d' % ebank)
    with open(os.path.join(ROOT, 'boot_cfg.inc'), 'w', encoding='latin-1',
              newline=nl) as f:
        f.write(hdr)
        f.write(f'BOOT_TOPBANK equ ${top:02X}' + nl)
        f.write(f'B_MCOL       equ {MARK_COL}' + nl)
        f.write(f'BOOT_RELOC   equ ${BOOT_RELOC:04X}' + nl)
    with open(os.path.join(ROOT, 'boot_rows.inc'), 'w', encoding='latin-1',
              newline=nl) as f:
        f.write(nl.join(out) + nl)
    print(f'  wrote boot_cfg.inc + boot_rows.inc  (linear RAM $01-${top:02X}, V{version()})')


if __name__ == '__main__':
    main()
