#!/usr/bin/env python3
"""Generate trig + reciprocal tables for the BSP renderer -> trig.inc, recip.inc.

sin/cos as 16-bit SIGNED Q14 (value = round(sin(a)*16384)), 256 BAM entries
(a = i/256 of a full turn). Stored as low/high byte tables for 6502 indexing.
Matches render_fixed.py's TRIG=14 fixed-point so the ASM transform reproduces
the validated Python math.

recip.inc: two normalized 1/mantissa tables that replace udiv16/udiv24 in
scale_z / screenx_signed (the per-seg bottleneck, ~4.5x faster -- see
tools/_recip_vs_div.py + _recip_shots.py). 256 entries each, indexed by Z's top
RBITS=9 bits (mantissa m in [256,511]). The focal/scale NUMERATOR is baked in so
each asm path is one lookup + (at most one 16x16 umul16) + a small shift -- no
24-bit divide, no big LUT, any Z:
  SCALE_TAB[m] = round((VFOCAL<<SF) * 2^SCALE_K / m)  -> scale = SCALE_TAB[m] >> (SCALE_K+e)
  SX_TAB[m]    = round(FOCAL        * 2^SX_K    / m)  -> off   = (|X|*SX_TAB[m]) >> (SX_K+e)
These constants MUST match gui.py so the spec and the 6502 stay bit-identical.
"""
import math
import os

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # build icl's from root
OUT = os.path.join(_ROOT, 'trig.inc')
OUT_RECIP = os.path.join(_ROOT, 'recip.inc')
Q = 14
RBITS = 9                 # mantissa bits (matches gui._RBITS)
VFOCAL = 160              # vertical focal (scale_z numerator = VFOCAL<<SF)
SF = 8
FOCAL = 80               # horizontal focal = screen half (screenx)
SCALE_K = SF             # scale = (VFOCAL<<SF)/Z = SCALE_TAB[m] >> (SCALE_K + e)
SX_K = 17                # screenx off = FOCAL*|X|/Z = (|X|*SX_TAB[m]) >> (SX_K + e)
INV_K = 23               # inv_span: INV_TAB[m]=round(2^INV_K/m); step=(R-L)*INV_TAB[m]>>(INV_K+e)


def rows(vals, lohi):
    out = []
    for i in range(0, 256, 16):
        chunk = vals[i:i + 16]
        if lohi == 'lo':
            bs = [v & 0xFF for v in chunk]
        else:
            bs = [(v >> 8) & 0xFF for v in chunk]
        out.append('        dta ' + ','.join(f'${b:02X}' for b in bs))
    return '\n'.join(out)


def main():
    sin = [int(round(math.sin(i * 2 * math.pi / 256) * (1 << Q))) for i in range(256)]
    cos = [int(round(math.cos(i * 2 * math.pi / 256) * (1 << Q))) for i in range(256)]
    with open(OUT, 'w', encoding='ascii') as f:
        f.write('; AUTO-GENERATED by bsp/gen_tables.py -- do not edit.\n')
        f.write(f'; sin/cos Q{Q} (signed 16-bit), 256 BAM entries. lo/hi byte tables.\n\n')
        f.write('        .align $100\n')
        f.write('SIN_LO\n' + rows(sin, 'lo') + '\n')
        f.write('SIN_HI\n' + rows(sin, 'hi') + '\n')
        f.write('COS_LO\n' + rows(cos, 'lo') + '\n')
        f.write('COS_HI\n' + rows(cos, 'hi') + '\n')
    print(f'wrote {OUT} (sin/cos Q{Q}, 256 entries)')

    # baked reciprocal tables, mantissa m in [2^(RBITS-1), 2^RBITS), index m-lo
    lo, hi = 1 << (RBITS - 1), 1 << RBITS
    scale_tab = [(((VFOCAL << SF) << SCALE_K) + m // 2) // m for m in range(lo, hi)]
    sx_tab = [((FOCAL << SX_K) + m // 2) // m for m in range(lo, hi)]
    inv_tab = [((1 << INV_K) + m // 2) // m for m in range(lo, hi)]   # generic 1/mantissa
    for nm, t in (('SCALE_TAB', scale_tab), ('SX_TAB', sx_tab), ('INV_TAB', inv_tab)):
        assert len(t) == 256 and max(t) <= 0xFFFF, (nm, len(t), max(t))
    with open(OUT_RECIP, 'w', encoding='ascii') as f:
        f.write('; AUTO-GENERATED by tools/gen_tables.py -- do not edit.\n')
        f.write(f'; normalized reciprocal (any Z): mantissa m = top {RBITS} bits of Z, '
                f'exponent e. m index = m-{lo}.\n')
        f.write(f';   SCALE_TAB[m] = round((VFOCAL<<SF)<<{SCALE_K} / m); '
                f'scale_z  = SCALE_TAB[m] >> ({SCALE_K}+e)\n')
        f.write(f';   SX_TAB[m]    = round(FOCAL<<{SX_K} / m);            '
                f'screenx  = (|X|*SX_TAB[m]) >> ({SX_K}+e)\n')
        f.write(f'RECIP_RBITS equ {RBITS}\n')
        f.write(f'RECIP_SCALE_K equ {SCALE_K}\n')
        f.write(f'RECIP_SX_K    equ {SX_K}\n\n')
        f.write('        .align $100\n')
        f.write('SCALE_TAB_LO\n' + rows(scale_tab, 'lo') + '\n')
        f.write('SCALE_TAB_HI\n' + rows(scale_tab, 'hi') + '\n')
        f.write('SX_TAB_LO\n' + rows(sx_tab, 'lo') + '\n')
        f.write('SX_TAB_HI\n' + rows(sx_tab, 'hi') + '\n')
        f.write(f'RECIP_INV_K equ {INV_K}\n')
        f.write('INV_TAB_LO\n' + rows(inv_tab, 'lo') + '\n')
        f.write('INV_TAB_HI\n' + rows(inv_tab, 'hi') + '\n')
    print(f'wrote {OUT_RECIP} (SCALE_TAB + SX_TAB + INV_TAB, 256 entries each, m in [{lo},{hi}))')


if __name__ == '__main__':
    main()
