#!/usr/bin/env python3
"""Quarter-square multiply tables -> qs_tables.inc + qs_mirror.inc.

f(n) = floor(n*n/4), and the identity every multiply in this engine rests on:

    a*b = f(b+a) - f(b-a)          (exact for integers, f even)

qs_tables.inc (the LEGACY layout, unchanged in content) holds f over 0..511 as
four 256-byte pages so `lda QSqr*,Y` can index it with an 8-bit register; the
qsmul macro in math.asm picks Base or Ext on the 9-bit sum's carry and takes
the absolute value of the difference itself.

qs_mirror.inc is what makes b. Fox/Tqa's fmulu_8x8 possible
(_pomocne/mads-src/math/fmulu_8x8.asm): with ONE operand baked into the
instruction's address, the other one indexes both tables and the branch AND the
absolute value disappear --

    base1 = SQ1 + b      -> SQ1[b + a] = f(b+a)
    base2 = SQ2 + 255-b  -> SQ2[255-b+a] = f(a-b)      (SQ2[m] = f(m-255))

so the whole product is `sec / lda base1,y / sbc base2,y / lda base1h,y /
sbc base2h,y`. It pays off exactly where one operand is constant over many
products -- paint.asm's pt_dy multiplies every run length in a column by the
same rs_rpt, so the four base bytes are patched once per COLUMN and each run
costs ~20 cycles instead of ~40.

That needs f laid out CONTIGUOUSLY over 0..511 (Base then Ext, not Base/Hi/
Ext/Hi), which is why this file emits qs_tables.inc too: same bytes, order
changed, plus the SQ1L/SQ1H aliases. The mirror is 1 KB and lands on the base
RAM the painted build freed (memory_map.inc TEXIX_BASE -- the column index
moved to SDRAM with the runs).

  python tools/gen_qs.py
"""
import os

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(_ROOT, 'qs_tables.inc')
OUT_MIRROR = os.path.join(_ROOT, 'qs_mirror.inc')

HDR = """;--------------------------------------------------------------
; RAM BUDGET: see the RAM-BUDGET block at the top of memory_map.inc, or run
;   `python tools/ram_map.py`.
;--------------------------------------------------------------
; AUTO-GENERATED by tools/gen_qs.py -- do not edit.
"""


def rows(vals, shift):
    out = []
    for i in range(0, len(vals), 16):
        chunk = vals[i:i + 16]
        out.append('        dta ' + ','.join(f'${(v >> shift) & 0xFF:02X}'
                                             for v in chunk))
    return '\n'.join(out)


def main():
    f = [(n * n) // 4 for n in range(512)]
    with open(OUT, 'w', encoding='ascii') as fh:
        fh.write(HDR)
        fh.write("""; f(x) = floor(x^2 / 4), x in 0..511.  a*b = f(a+b) - f(|a-b|).
;   The four legacy labels are unchanged in MEANING -- Base is x in 0..255, Ext
;   is x in 256..511 -- but the ORDER is now Lo,Lo,Hi,Hi so that the low bytes
;   are one contiguous 512-byte table (SQ1L) and the high bytes another (SQ1H).
;   That is what lets pt_dy address them with a patched base (see gen_qs.py and
;   _pomocne/mads-src/math/fmulu_8x8.asm). qsmul (math.asm) is untouched: it
;   still indexes each 256-byte page with Y.
;   Page-aligned so `lda QSqr*,Y` never pays the cross-page +1 cycle.
;==============================================================

        .align $100
SQ1L
QSqrLoBase
""")
        fh.write(rows(f[:256], 0) + '\n')
        fh.write('QSqrLoExt\n' + rows(f[256:], 0) + '\n')
        fh.write('SQ1H\nQSqrHiBase\n' + rows(f[:256], 8) + '\n')
        fh.write('QSqrHiExt\n' + rows(f[256:], 8) + '\n')
        # THE TAIL GUARD. It was hand-written into the generated file and this
        # generator never emitted it, so the first `python tools/gen_qs.py`
        # deleted it (2026-08-29). Both .inc files were hand-edited after
        # generation -- the mirror's org and this guard -- and neither edit came
        # back here, which is exactly how a generator and its output drift apart.
        fh.write("""; 2026-08-11 pm: this KB lives at TEXIX_BASE ($6100, win1 = FAST) since it
; swapped homes with qs_mirror.inc -- qsmul reads it on every umul16 and it was
; costing 11.1 ms/frame in win2 (bsp_main.asm's icl site has the measurement).
; TEXIX_MAX is the ceiling the column-index blob would have used here.
    .if * > TEXIX_BASE+TEXIX_MAX
        ert 'qs_tables.inc outgrew the freed TEXIX_BASE block (memory_map.inc)'
    .endif
""")
    print(f'wrote {OUT} (f(x) 0..511, SQ1L/SQ1H contiguous)')

    g = [f[abs(m - 255)] for m in range(512)]      # SQ2[m] = f(m-255)
    with open(OUT_MIRROR, 'w', encoding='ascii') as fh:
        fh.write(HDR)
        fh.write("""; SQ2[m] = f(m - 255), the MIRRORED quarter-square table. With base2 =
;   SQ2 + (255-b) the index a reads f(a-b) with no absolute value and no
;   branch -- see gen_qs.py's header and pt_dy in paint.asm.
;   Only the painted build assembles it.
; 2026-08-31: the tables RUN at SQ2L_HOME/SQ2H_HOME -- under-ROM RAM, fast,
;   dead in the shipped XEX (SGOVL's lifted parking) -- and the XEX PARKS the
;   bytes at SQ2L_STAGE/SQ2H_STAGE in win2 (two-address org, the overlay
;   trick). b1_to_ext copies the staged bytes to the bank $01 masters at boot
;   and init_level's `jsl b1_sq2_restore` repaints the homes after every
;   level load (load_things streams the THINGS blob straight over them).
;   All five addresses live in memory_map.inc; this file only spends them.
;   The win2 read cost this killed: 12,172 reads/frame at x11.2 = 5.8 ms.
;==============================================================
    .if TEX_RUNS
; SQ2H comes FIRST on purpose: MADS merges a two-address org into the open
; segment when its RUN address equals the current one -- adr2 and all -- so
; SQ2L-then-SQ2H (runs $C900, $CB00 = contiguous) parked BOTH tables at
; SQ2L_STAGE and ran the segment into the MEMAC window. H-then-L makes each
; org's run address discontiguous with the previous stream, forcing the two
; file headers this layout needs (caught by check_xex, 2026-08-31).
qsm_resume = *
        org SQ2H_HOME, SQ2H_STAGE
SQ2H
""")
        fh.write(rows(g, 8) + '\n')
        fh.write("""    .if * > SQ2H_HOME+$200
        ert 'SQ2H outgrew its page pair (memory_map.inc SQ2H_HOME)'
    .endif
        org SQ2L_HOME, SQ2L_STAGE
SQ2L
""")
        fh.write(rows(g, 0) + '\n')
        fh.write("""    .if * > SQ2L_HOME+$200
        ert 'SQ2L outgrew its page pair (memory_map.inc SQ2L_HOME)'
    .endif
        org qsm_resume
    .endif
""")
    print(f'wrote {OUT_MIRROR} (SQ2 mirror: runs at SQ2L_HOME/SQ2H_HOME, parks at *_STAGE)')
    # the identity, checked here so the asm never has to be trusted on it
    for a in (0, 1, 7, 63, 128, 200, 255):
        for b in (0, 1, 3, 16, 100, 255):
            assert f[b + a] - g[255 - b + a] == a * b, (a, b)
    print('  identity f(b+a) - SQ2[255-b+a] == a*b verified')


if __name__ == '__main__':
    main()
