#!/usr/bin/env python3
"""Emit atari_pal.inc -- the STOCK Atari 256-colour palette, for putting VBXE
palette 0 back the way the machine found it.

WHY THIS EXISTS. The port needs four palettes (normal + two damage reds + the
pickup gold, pack_textures.PAL_SLOTS) and VBXE has exactly four, so palette 0
is one of them. Palette 0 is also what VBXE maps ordinary GTIA colours through,
and a WARM reset does not restore it: Altirra's own core only refills it in
ColdReset (_pomocne/alt-src/Altirra/source/vbxe.cpp:226-227), while WarmReset
(:277-300) just turns the XDL and the MEMAC windows off. So after RESET the OS
screen is drawn with DOOM's palette -- which is mostly dark -- and the machine
looks dead until a power cycle or SVBXE.SYS.

The fix is to write this table back into palette 0 from a DOSINI hook
(resetpal.asm). It is the classic NTSC hue-angle construction rather than a
capture of any particular core's ROM table: the goal is "the OS screen looks
normal again", not colorimetry, and every 8-bit palette in circulation differs
in the third digit anyway.

  python tools/gen_atari_pal.py
"""
import math
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(_HERE), 'atari_pal.inc')

HUE_START = -58.0        # degrees of the first non-grey hue
HUE_STEP = 25.7          # per hue step -- 14 steps just over a full turn
SAT = 0.30
GAMMA = 1.0              # VBXE holds plain 8-bit RGB; no correction wanted


def palette():
    out = []
    for hue in range(16):
        for lum in range(16):
            y = lum / 15.0
            if hue == 0:
                r = g = b = y
            else:
                a = math.radians(HUE_START + (hue - 1) * HUE_STEP)
                i, q = SAT * math.cos(a), SAT * math.sin(a)
                r = y + 0.956 * i + 0.621 * q
                g = y - 0.272 * i - 0.647 * q
                b = y - 1.107 * i + 1.704 * q
            out.append(tuple(
                max(0, min(255, int(round(255 * (max(0.0, min(1.0, c)) ** GAMMA)))))
                for c in (r, g, b)))
    return out


def main():
    pal = palette()
    lines = [
        '; AUTO-GENERATED by tools/gen_atari_pal.py -- do not edit.',
        '; The stock Atari 256-colour palette, R,G,B per index, for restoring',
        '; VBXE palette 0 after a warm reset (resetpal.asm). See that tool for why.',
        'atari_pal',
    ]
    for i in range(0, 256, 8):
        row = ', '.join(f'${r:02X},${g:02X},${b:02X}' for r, g, b in pal[i:i + 8])
        lines.append(f'        dta {row}')
    with open(OUT, 'w', encoding='ascii') as f:
        f.write('\n'.join(lines) + '\n')

    # the two the OS text screen actually uses, as a sanity check
    for name, idx in (('COLOR2 $94 (background)', 0x94),
                      ('COLOR1 $0A (text)', 0x0A),
                      ('black  $00', 0x00)):
        r, g, b = pal[idx]
        print(f'  {name:24} -> #{r:02X}{g:02X}{b:02X}')
    print(f'{OUT}: {3 * len(pal)} B')
    return 0


if __name__ == '__main__':
    sys.exit(main())
