#!/usr/bin/env python3
"""THE RAM budget: what is occupied at runtime, and what is left for new code.

This is the single source of truth for the RUNTIME picture. memory_map.inc owns
the addresses; this file owns the knowledge of which RAM is *destroyed later* and
therefore cannot hold code even though no XEX segment claims it. That distinction
is not visible to MADS: the assembler happily places code at $B000, and the level
loader then streams textures over it -- the symptom is a flat pink screen at boot,
with no error anywhere. It has already cost one debugging session.

  python tools/ram_map.py                    # print the budget
  python tools/ram_map.py --update           # rewrite the block in memory_map.inc
  python tools/check_xex.py <xex>            # fail the build on any overlap

RESERVED is imported by tools/check_xex.py so the two can never drift apart.

HOW TO READ THE MAP WHEN YOU NEED SPACE (2026-08-20, written down after an hour
of looking for 30 bytes and finding them three times where they were not):

  1. "FREE RAM FOR NEW CODE: NONE" below is the truth, and it is a truth about
     a 64 KB machine that is FULL, not about fragmentation. The accounting:
     ~47.4 KB of XEX code+data, ~16.4 KB of RAM that carries no XEX segment but
     is written at RUNTIME (the $4000 map slot, the $C000 things slot, the
     $1000 SIO staging, the $9000 VBXE MEMAC-A window, the under-ROM blob
     landing zones -- that is what RESERVED lists), and the 2 KB hardware hole
     at $D000-$D7FF. There is nothing behind the XEX to discover.

  2. DO NOT trust a gap between XEX segments (tools/tests/_probe_holes.py).
     Equated variables carry no segment, so a "20 byte hole" at $E6C3 is
     MV_SPD, the mover speed array, and code parked there is overwritten by the
     first lift that moves. RESERVED exists precisely because MADS cannot see
     this, and RESERVED does not list every variable -- cross-check the .lab.

  3. DO NOT trust a block's declared _END either. ~150 of the _BASE/_END pairs
     in memory_map.inc OVERLAP another pair: the big blocks were subdivided
     over time and the outer _END was left as a stale upper bound. APREF_END
     ($81FF) is the clearest case -- arena_prefetch really ends at $80F4 and
     MTXPEG/PAINROW/SWFIRE own everything above it, so that block's `ert` guard
     would not fire until the proc had already eaten mtx_pegf. A block's REAL
     slack is (the next _BASE above it) minus (where its code actually ends in
     build/doom_bsp.lst), never _END minus that.

  4. So the only way to add code is the one the budget says: EVICT. Move a cold
     proc to a Rapidus bank or under the ROM, or -- cheaper and what the
     cacodemon's A_HeadAttack did on 2026-08-20 -- change the DATA LAYOUT so
     the new thing needs no new bytes at all (there, renumbering mk_atk so the
     four missile actions stayed contiguous kept at_tables.inc four rows wide
     and paid for the feature out of two bytes saved in ai_fire's dispatch).
"""
import os
import re
import struct
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(_HERE)
XEX = os.path.join(ROOT, 'build', 'doom_bsp.xex')
INC = os.path.join(ROOT, 'memory_map.inc')


def _things_slot_end():
    """load_things streams PIECE 1 of the blob -- THINGS_SECT whole sectors --
    to $C000, so the zero padding behind it lands in RAM too. The reserve must
    cover the SLOT, not the biggest blob: 2026-08-04 the blobs grew to 30
    sectors, the padding reached $CEFF and wiped switch_match at $CECA -- the
    first USE at any switch hit a BRK (the E1M8 start-switch freeze).
    2026-08-29: the count comes from memory_map.inc's THINGS_SECT, not from
    atr_layout's THG_SECTORS -- the latter covers BOTH pieces now, and piece 2
    lands at THINGS2_BASE ($DA00), which has a reserve of its own below."""
    try:
        src = open(os.path.join(ROOT, 'memory_map.inc')).read()
        n = int(re.search(r'^THINGS_SECT\s+equ\s+(\d+)', src, re.M).group(1))
        return 0xC000 + n * 128 - 1
    except (OSError, AttributeError):
        return 0xCF7F

def _tex_runs():
    """Is this a PAINTED-wall build? pack_map.py writes the flag into
    map_syms.inc, and with it on the column index never reaches base RAM at all
    (texcol.asm reads it from SDRAM), so $6100 stops being reserved and becomes
    where the mirrored quarter-square table lives (qs_mirror.inc)."""
    try:
        src = open(os.path.join(ROOT, 'map_syms.inc')).read()
        return bool(re.search(r'^TEX_RUNS\s+equ\s+1', src, re.M))
    except OSError:
        return False


BEGIN = ';>>> RAM-BUDGET (generated by tools/ram_map.py -- do not edit by hand)'
END = ';<<< RAM-BUDGET'

# RAM that is spoken for at RUNTIME but carries no XEX segment. Code placed in any
# of these is silently destroyed. Keep in sync with memory_map.inc.
# OS-owned low RAM: never free, but the XEX legitimately puts the zero-page block,
# early_init and the RUNAD/INITAD vectors there, so it is NOT part of the overlap
# check -- only of the free-space computation.
# 2026-07-31: split around $0340-$03E7. Per the OS source
# (_pomocne/A800-OS-XL-Rev2-main/Atari_XL_OS_Rev.2.lab) that range is the eight
# 16-byte IOCBs ($0340-$03BF) plus PRNBUF ($03C0-$03E7) -- CIO and the printer.
# This port never calls CIOV: every load goes through SIOV, which uses the DCB at
# $0300-$030B and nothing above it. So the range is real, contiguous, free RAM.
# NOT taken, deliberately: $031A HATABS (CIO handler table, cheap to leave alone)
# and $03F8-$03FC BASICF/MINTLK/GINTLK/CHLINK -- the OS VBI reads the cartridge
# interlock and a wrong value there cold-starts the machine.
OS_LOW = [
    (0x0000, 0x033F, "OS zero page / stack / shadow registers / DCB"),
    (0x03E8, 0x05FF, "OS flags (GINTLK!), cassette buffer, FP scratch"),
]

RESERVED = [
    # $0340-$0353: PAINT_VARS, the run painter's per-column working set
    # (memory_map.inc). Equated variables carry no XEX segment, so without this
    # line the budget below offers those 20 bytes as free code space -- the same
    # trap rs_utL/rs_utR at $03C1 sit in, one block further up.
    # ... +0x0357 = EXTRALIGHT, the muzzle flash's 0/2/4 (memory_map.inc,
    # lights.asm wp_flight/lt_seg_flash, 2026-08-31).
    (0x0340, 0x0357, "PAINT_VARS + EXTRALIGHT: paint.asm per-column state / muzzle flash"),
    # ...and the two the line above already named as the same trap "one block
    # further up" without ever reserving them: rs_utL/rs_utR = OSFREE_BASE+$81/
    # +$83 (memory_map.inc). They sat inside the 39 B block the budget offered
    # as its second-biggest free hole, so a proc parked at $03C1 would have been
    # overwritten by the painter's u-track step (2026-08-08).
    (0x03C1, 0x03C4, "rs_utL/rs_utR: paint.asm u-track step (memory_map.inc)"),
    # 2026-08-11: the triple-buffer flip state -- equs with no XEX segment, the
    # same trap as PAINT_VARS above. ZFRONT = the published buffer (mn_freeze
    # reads it), FRM_PAR = the spectre-fuzz frame parity.
    (0x06EC, 0x06ED, "ZFRONT/FRM_PAR: triple-buffer flip state (memory_map.inc)"),
    # $0700-$08FF: the boot loader dies after load, but the CLIP POOL ($0700)
    # and the vissprite arrays vs_xb..vs_scl ($0800) live there at RUNTIME.
    (0x0700, 0x08FF, "boot loader during load; clip pool + vissprite arrays at runtime"),
    # 2026-08-08: ANVARS, the animated-texture rings' cursor + countdown
    # (an_i[16]/an_t[16]/an_n, memory_map.inc ANVARS_BASE..END). Same equ-with-no-
    # XEX-segment trap as vs_ybt and vs_th below, and it had already put a whole
    # 42 B block at the TOP of the budget's "FREE RAM FOR NEW CODE" list -- code
    # parked there assembles clean, boots clean and dies the first time an_tick
    # runs. Found while taking an_init's slack at $17B7 for en_bossdie, which
    # promoted this block to the biggest one on offer.
    (0x0CC2, 0x0CEB, "ANVARS: animated-texture ring cursors (memory_map.inc)"),
    # 2026-07-25: was $0F00-$0F57 only, so everything the engine keeps in equs above
    # it (tex_off/key_prev at $0F58, THING_ALIVE[128] at $0F60, PSTATE at $0FE0) plus
    # the sprite scratch + door tables at $0E9E-$0EFF were advertised as FREE code
    # space -- a relocated proc parked at $0F58 silently ate the render toggles.
    (0x0E9E, 0x0FFF, "sprite scratch, door tables + state, render toggles, THING_ALIVE, PSTATE"),
    (0x1000, 0x13FF, "per-frame render arrays + rs_*/tw_* scratch + the 1 KB SIO staging (TEX_STAGE)"),
    (0x1400, 0x14FF, "bsp_stack (BSP walk)"),
    # 2026-08-01: vs_ybt, the vissprite BOTTOM-row array en_seen needs to answer
    # "is this thing visible in the centre column" (the height fix). It is an equ
    # in the tail of the $2000 engine segment with no XEX segment behind it, so
    # without this entry free_blocks() offers $3DB0 as code space and the next
    # relocated proc parks on top of every hitscan.
    (0x3DB0, 0x3DD7, "vs_ybt: vissprite last-row array (memory_map.inc)"),
    # 2026-08-31: the frac tables moved to Rapidus bank $01 ($9900-$9EFF,
    # memory_map.inc FRAC_EXT) -- their old $8D00/$A800 win2 pages now park the
    # STAGED SQ2 master data (real XEX segments, so no entry is needed here)
    # and are dead once b1_to_ext has copied them up.
    # 2026-07-31: the seg records (14,896 B, $47F0-$821F) went to Rapidus bank
    # $03 and the slot collapsed from 17.9 KB to the 2.7 KB of header + sectors
    # + textab + yoffs. $4C00-$85FF is ordinary RAM now -- and per Altirra
    # rapidus.cpp kSRAMWindows the $4000-$7FFF half of it can be a FAST SRAM
    # window, unlike $8000-$BFFF. Keep this bound in step with pack_map.py
    # LOW_LIMIT: that is what fails the pack if a level set outgrows it.
    (0x4000, 0x4BFF, "streamed map slot (LOW) -- load_level overwrites it"),
    # 2026-08-01: the texture COLUMN INDEX table (pack_textures.dedup_columns).
    # It is not an XEX segment -- tex_getix copies it out of the MEMAC window
    # after every level load -- so without this entry free_blocks() would offer
    # $6100 as code space and the next level load would eat whatever landed
    # there. Keep in step with TEXIX_BASE/TEXIX_MAX in memory_map.inc.
] + ([] if _tex_runs() else [
    (0x6100, 0x677F, "texture column index table (streamed via the .tex blob)"),
]) + [
    (0x9000, 0x9FFF, "MEMAC-A window: writes go to VBXE, not RAM"),
    # 2026-07-28: the vissprite RECORDS went per-field ($0800 page + $BF50+),
    # so $BAC0-$BF4F freed up -- coll_seg/collide_leaf (COLLFAST) live there now.
    # 2026-08-30: hud_ent, the 7-byte row hud_entry copies down out of
    # Rapidus bank $01. An equ with no XEX segment -- the PAINT_VARS/vs_ybt
    # trap again, and without this line free_blocks() offers $BE60 at the
    # TOP of its list (the 205 B the table itself freed).
    (0xBE60, 0xBE66, "hud_ent: the HUD_TAB row hud_entry fetched (memory_map.inc)"),
    (0xBF50, 0xBFFF, "vissprite arrays vs_sch/cpl/sid/ord (sprites.asm)"),
    # 2026-08-02: vs_th and USE_PT. Both are equs with no XEX segment, so
    # free_blocks() advertised them as code holes ("$E6F8-$E71F 40 B",
    # "$E73D-$E75F 35 B") -- and a relocated proc parked at $E6F8 assembled
    # clean, booted clean, and then died the first time a lift was triggered:
    # spr_add rewrites vs_th every frame, so the routine was sprite data by the
    # time anything called it (strange sound, then a hang). Same class of bug as
    # the vs_ybt entry above. If VIS_MAX or the USE ray's point list ever grows,
    # these bounds must follow.
    (0xE6F8, 0xE71F, "vs_th: [VIS_MAX] vissprite THING index (memory_map.inc)"),
    (0xE740, 0xE74F, "USE_PT: [16] the USE ray's point list (memory_map.inc)"),
    # 2026-07-25: $C000-$FFFF is now USED -- underrom.asm banks the OS ROM out
    # (PORTB bit0) around calls into the cold code that lives there, and the boot
    # loader stores those segments with the ROM banked out. Only the hardware
    # window inside it stays untouchable.
    # 2026-07-27: ... and the STREAMED under-ROM targets are reserved here too.
    # They are not XEX segments, so free_blocks() advertised them as free code
    # space -- code parked at $C000 assembled + booted clean and then died on
    # the first level load, when load_things streamed the blob over it (pink
    # screen, crash PC mid-blob at $C0D1). If a streamed region ever moves or
    # grows, THIS list must follow it, or the next relocation repeats that.
    (0xC000, _things_slot_end(),
     "THINGS slot incl. sector padding (load_things streams THG_SECTORS x 128 B)"),
    (0xD000, 0xD7FF, "hardware (GTIA/POKEY/PIA/ANTIC/VBXE) -- not RAM at all"),
    # 2026-07-28: NODES moved to the Rapidus EXT bank, so the streamed HIGH
    # region (SECTORS is LOW now too -- ssectors + door records) ends well below
    # $E300; USERAY/MVUSED/SEGYOFF code lives at $E300+ (pack_map.py HI_LIMIT
    # fails the pack before the stream could ever reach them).
    # 2026-08-29: HIGH keeps its four sectors and the tail it never used since
    # SSECTORS left goes to the .things blob's SECOND piece (memory_map.inc
    # THINGS2_BASE, pack_map.py HI_LIMIT). Both are streamed, neither is an XEX
    # segment, so both have to be here.
    (0xD800, 0xD9FF, "map HIGH region (doors + doorlock, streamed -- pack_map.py)"),
    (0xDA00, 0xE17F, "THINGS blob piece 2 (triggers.., streamed -- pack_things.py)"),
    # 2026-08-18: the 12 door arrays left $F000 for Rapidus bank $01 (DOOR_EXT,
    # memory_map.inc) so DOORS_NMAX could go 32 -> 48 and E2/E3 stopped needing
    # welded-open doors. $F000-$F17F is ordinary under-ROM code space again --
    # 384 B, which is where any block that outgrew itself on the way should go.
    # Nothing to reserve here any more; bank $01 carries no XEX segment at all.
    # 2026-07-29: the floor engine went MV_NMAX slots wide; its 10 parallel
    # arrays are runtime data at MV_TAB with no XEX segment behind them, so the
    # hole above use_ray must be reserved or a relocated proc lands on top of
    # every lift in the game.
    # 2026-08-02: 20 slots x 10 B. It was 4 slots in the 64 B hole above use_ray
    # ($E3C0-$E3FF, free again now) until stairs started creeping up instead of
    # snapping -- EV_BuildStairs arms every step at once and each holds a slot
    # until it arrives, so E1M8's flight alone wants 14.
    (0x7200, 0x72C7, "MV_TAB: the MV_NMAX floor-mover slots (movers.asm)"),
    (0xFFFA, 0xFFFF, "RAM interrupt vectors (urom_init)"),
]

# STAGING segments: XEX segments that deliberately land in RESERVED RAM because
# they are copied OUT before whatever reserves it ever runs. check_xex.py skips
# a segment contained in one of these, and free_blocks() must not count the RAM
# as free either -- it is the reserve's, not ours.
#   $4000  RECIP_STAGE: the 6 reciprocal-table pages ride into the map slot and
#          recip_to_ext copies them to Rapidus bank $01 (memory_map.inc
#          RECIP_EXT) during init, well before the first load_level. After that
#          the segment is dead RAM the level stream overwrites, as intended.
STAGED = [
    # 6 pages of table + recip_to_ext itself, which rides along in the same
    # segment so the copy costs no permanent RAM either.
    (0x4000, 0x4BFF, "RECIP_STAGE -> bank $01, then menu.asm's loaders "
                     "(both die at load_level)"),
    # 2026-08-08: menu.asm used to stage its cold half in bsp_stack as well. It
    # does not any more -- the menu is on ESC now, so the whole of it moved to
    # the VRAM overlay at $00E000 that mn_open copies down into $1000-$14FF on
    # demand (menu.asm's header). tools/split_menu_ovl.py takes that block out
    # of the XEX before check_xex.py runs, so there is no segment to carry here.
    # 2026-08-08: xdl.asm -- the 650 B stretched display list + the loop that
    # copies it into VBXE banks $08/$09. setup_xdl runs it before the first SIO
    # call, so the staging buffer is still ours; afterwards every loader is
    # welcome to it.
    (0x1000, 0x13FF, "TEX_STAGE -> xdl.asm (built into VRAM before the first load)"),
    # 2026-08-26: bank01.asm. Whole PROCEDURES staged here and copied into
    # Rapidus SRAM bank $01, where the 65816 runs them at full speed; what
    # stays behind at each old address is a 5-byte `jsl/rts` thunk, so no call
    # site had to change. The gap between menu.asm's overlay ($C000-$C4F8) and
    # savegame.asm's ($C800-) -- b1_to_ext copies it out before the first
    # load_things, and the things slot then has it back.
    (0xC500, 0xC7FF, "B1CODE_STAGE -> bank $01 (bank01.asm), then the things slot"),
    # 2026-08-31: the SECOND bank01 block (b1_build_frac + b1_amgate),
    # staged in the raw-XEX hole behind SGOVL's parking. Copied up by the same
    # b1_to_ext pass; the things stream owns the pages afterwards. The SQ2
    # (The $C900 SQ2-home scheme this once served is gone -- the tables live
    # at SQ2L_UROM/SQ2H_UROM now, past every stream.)
    (0xCD00, 0xCF7F, "B1CODE2_STAGE -> bank $01 (bank01.asm), then the things slot"),
    # 2026-08-31 pm: the automap overlay stopped riding menu.bin -- the XEX
    # keeps its two-address-org segment at AMOVL_STAGE and b1_to_ext copies it
    # to bank $01 (AMOVL_EXT) before the first level load streams doors/things
    # over these pages.
    (0xD800, 0xDCFF, "AMOVL_STAGE -> bank $01 (automap.asm), then map HIGH + things2"),
    # 2026-08-25: sound_tables.inc's five per-SFX arrays (280 B) stage in the gap
    # BEHIND xdl.asm's display-list data ($1302-$1340 is the last of it) and run
    # on into bsp_stack. recip_to_ext's tail (snd_to_ext) copies them to Rapidus
    # bank $01 at $0239 -- after setup_xdl has finished with TEX_STAGE, before
    # the first SIO call touches it and long before the first frame rebuilds
    # bsp_stack. What it bought is 280 B at $3DD8 in a Rapidus-FAST window for
    # the sight ray's z test (memory_map.inc SGZ_BASE / SNDX_STAGE).
    (0x1341, 0x14FF, "SNDX_STAGE -> bank $01 (snd_to_ext, before the first SIO)"),
]

# Reserves: real RAM we could take back, and what it costs.
# (The old "under-ROM RAM unused" lines are gone: $C000-$CBFF is the streamed
#  THINGS blob and $D800-$F7FF the streamed map HIGH region -- see RESERVED.)
RECLAIMABLE = []


def segments(path=XEX):
    """Parse a segmented Atari XEX -> [(start, end)]."""
    d = open(path, 'rb').read()
    out, i = [], 2
    while i + 4 <= len(d):
        s, e = struct.unpack('<HH', d[i:i + 4])
        i += 4
        if s == 0xFFFF:                      # extra $FFFF header, skip
            continue
        out.append((s, e))
        i += e - s + 1
    return sorted(out)


def free_blocks(segs):
    used = sorted([(s, e) for s, e in segs] +
                  [(s, e) for s, e, _ in RESERVED + OS_LOW])
    free, cur = [], 0x0000
    for s, e in used:
        if s > cur:
            free.append((cur, s - 1))
        cur = max(cur, e + 1)
    if cur <= 0xFFFF:
        free.append((cur, 0xFFFF))
    return [(a, b) for a, b in free if b - a + 1 >= 32]


def render(segs):
    free = free_blocks(segs)
    total = sum(b - a + 1 for a, b in free)
    L = []
    A = L.append
    A(BEGIN)
    A(';')
    if free:
        biggest = max((b - a + 1, a, b) for a, b in free)
        A(';   FREE RAM FOR NEW CODE:  %d B total, biggest contiguous block %d B ($%04X-$%04X)'
          % (total, biggest[0], biggest[1], biggest[2]))
    else:
        # 2026-08-08: this used to be `max()` over an empty list, so the day the
        # map filled up the BUILD died with a ValueError instead of telling
        # anyone why. There is no block of >= 32 B left anywhere in the 64 KB.
        A(';   FREE RAM FOR NEW CODE:  NONE -- not one block of 32 B is left.')
        A(';   The next .proc has to EVICT something: move a cold one to bank $01')
        A(';   or under the ROM, or shrink a table. See the RESERVES below.')
    A(';')
    A(';   A procedure has to fit in ONE block, but it does not matter which: the')
    A(';   port already relocates code with `org` + absolute jsr (collision @ $0900,')
    A(';   check_bbox @ $1B00, tw_setup @ $8D00). When a segment outgrows its hole,')
    A(';   move a whole .proc out rather than letting the segment creep.')
    A(';')
    for a, b in free:
        n = b - a + 1
        note = ''
        if 0x2000 <= a < 0x4000:
            note = 'tail of the $2000 engine segment'
        elif 0x4000 <= a < 0x8600:
            note = 'the seg table left this (probably FAST below $8000)'
        elif 0x8600 <= a < 0x9000:
            note = 'below the MEMAC window'
        elif a >= 0xA000:
            note = 'MUST stay below $B000 (sprites.asm)'
        A(';     $%04X-$%04X  %5d B%s' % (a, b, n, '   ' + note if note else ''))
    A(';')
    A(';   RESERVES -- real RAM, but it costs something to take:')
    for a, b, why in RECLAIMABLE:
        A(';     $%04X-$%04X  %5d B   %s' % (a, b, b - a + 1, why))
    A(';')
    A(';   THE TRAP: MADS does NOT check any of this. Code assembled into RAM that')
    A(';   is overwritten later (the $1000-$13FF SIO staging TEX_STAGE, the $4000')
    A(';   map slot, the streamed under-ROM blobs) assembles clean and then dies')
    A(';   at boot with no message -- a flat pink screen. Guards:')
    A(';     * tools/check_xex.py fails the build on any overlap (build*.ps1)')
    A(';     * the RESERVED list in tools/ram_map.py -- keep it in step with the')
    A(';       loaders (diskio.asm), it is what check_xex enforces')
    A(';     * this block is regenerated by tools/ram_map.py on every build')
    A(END)
    return '\n'.join(L)


# EVERY hand-written asm/inc source carries the banner; ram_map keeps the figure
# in all of them honest. map_syms.inc / atr_layout.inc are generated, so their
# generators (tools/pack_map.py, tools/make_atr_doom.py) emit it themselves.
ASM_FILES = ['bsp_main.asm', 'renderer.asm', 'math.asm', 'collision.asm',
             'doors.asm', 'checkbbox.asm', 'vcache.asm', 'boot.asm',
             'viewsize.asm', 'read_keys.asm',
             'qs_tables.inc', 'recip.inc', 'trig.inc', 'vbxe_regs.inc',
             'atr_layout.inc', 'map_syms.inc']


def refresh_banners(total, biggest):
    """Keep the one-line figure in every .asm banner honest -- a stale number in
    eight files is worse than no number at all."""
    import re
    n = 0
    for f in ASM_FILES:
        path = os.path.join(ROOT, f)
        if not os.path.exists(path):
            continue
        s = open(path, encoding='utf-8', errors='replace').read()
        new = re.sub(r'; RAM BUDGET: \d+ B free, biggest contiguous block \d+ B\.',
                     '; RAM BUDGET: %d B free, biggest contiguous block %d B.' % (total, biggest),
                     s)
        if new != s:
            open(path, 'w', encoding='utf-8').write(new)
            n += 1
    return n


def main():
    if not os.path.exists(XEX):
        sys.exit('ram_map: %s not found -- build first' % XEX)
    block = render(segments())
    if '--update' in sys.argv:
        s = open(INC, encoding='utf-8').read()
        if BEGIN in s and END in s:
            i, j = s.index(BEGIN), s.index(END) + len(END)
            s = s[:i] + block + s[j:]
        else:
            anchor = ';==============================================================\n; 6502 RAM MAP (64 KB)'
            s = s.replace(anchor, block + '\n\n' + anchor, 1)
        open(INC, 'w', encoding='utf-8').write(s)
        free = free_blocks(segments())
        total = sum(b - a + 1 for a, b in free)
        biggest = max((b - a + 1 for a, b in free), default=0)
        n = refresh_banners(total, biggest)
        print('ram_map: memory_map.inc + %d .asm banners updated (%d B free)' % (n, total))
    print(block)


if __name__ == '__main__':
    main()
